### ISSUE TITLE
Avoid the call to "create extension" in PostgreSQL (only works as superuser)

### ISSUE THREAD

**Issue by erickrf** [danny-avila/rag_api#99]
I have a deployment of the RAG API with an existing instance of PostgreSQL, and I enable the vector extension separately.

Now, when I start the RAG API, it tries to run the `CREATE EXTENSION IF NOT EXISTS vector`, which fails because it isn't the database superuser, restarts and is caught into this loop.

I have tried giving the superuser to the RAG API in a development environment, and then it worked fine, but I cannot do that in production.

For reference, I'm using version 0.3.0 of the RAG API. For Postgres, I need to use a custom docker file mixing [Bitnami's PostgreSQL](https://hub.docker.com/r/bitnami/postgresql) 16.4 with the extension from [pgvector/pgvector](https://hub.docker.com/r/pgvector/pgvector) version 16.

**Comment by ScarFX** [comment]
The postsql command `CREATE INDEX IF NOT EXISTS` is found in `psql.py` in rag_api on line 32. 

Here is some of the code: 
```
async def ensure_custom_id_index_on_embedding():
    table_name = "langchain_pg_embedding"
    column_name = "custom_id"
    # You might want to standardize the index naming convention
    index_name = f"idx_{table_name}_{column_name}"

    pool = await PSQLDatabase.get_pool()
    async with pool.acquire() as conn:
        # Check if the index exists
        index_exists = await check_index_exists(conn, index_name)

        if not index_exists:
            # If the index does not exist, create it
            await conn.execute(f"""
                CREATE INDEX IF NOT EXISTS {index_name} ON {table_name} ({column_name});
            """)
            logger.debug(f"Created index '{index_name}' on '{table_name}({column_name})'")
        else:
            logger.debug(f"Index '{index_name}' already exists on '{table_name}({column_name})'")


async def check_index_exists(conn, index_name: str) -> bool:
    # Adjust the SQL query if necessary
    result = await conn.fetchval("""
        SELECT EXISTS (
            SELECT FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE  c.relname = $1 AND n.nspname = 'public' -- Adjust schema if necessary
        );
    """, index_name)
    return result
```
For whatever reason `check_index_exists(...)` is returning false when it should return true, since you said the vector extension is enabled.  This is where your issue most likely is (it would prevent `CREATE EXTENSION IF NOT EXIST vector` 

Perhaps the easiest way to get around this is to make sure the if statement is always false (or delete entirely). Then build the rag_api image from dockerfile not pulling it. 

Thanks for reaching out @erickrf . I am sure I know less than you about pgvector, but I will try to help if you any questions!

**Comment by erickrf** [comment]
Hi @ScarFX , I'm sorry but I think it was a false alarm, I misread the Postgres error logs (I was dealing with a lot of them!)

Since I ran the RAG API with the Postgres root user, the created tables belonged to the root, and when I tried a normal DB user, it didn't have access to the tables. Recreating the database solved the issue.
